apisix:
  ssl:
    enable: true
    enable_http2: true
    ssl_protocols: TLSv1.3
  proxy_mode: http&stream
  node_listen:
    - port: 80      # 외부 HTTP 트래픽용
    - port: 443     # 외부 HTTPS 트래픽용
    - port: 9080    # 기존 HTTP 트래픽 처리  
    - port: 9081
  enable_http2: true
  stream_proxy:
    tcp:
      - 6380 # listen on 9100 ports of all network interfaces for TCP requests
      - "127.0.0.1:6380"
    udp:
      - 9200 # listen on 9200 ports of all network interfaces for UDP requests
      - "127.0.0.1:9211"
  # lua_module_hook: "my_hook" # 사용자 정의 Lua 모듈 이름
  # extra_lua_path:
  #   - "/usr/local/apissix-plugin-lua/?.lua"

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  etcd:
    # 고가용성을 위해 두 서버의 etcd 엔드포인트 모두 지정
    host:
      - "http://10.101.99.100:2379"
      - "http://10.101.99.101:2379"
    prefix: "/apisix"
    timeout: 30 # etcd 응답 타임아웃(초 단위)
  admin:
    enable_admin_cors: true # Dashboard 연동 등에서 CORS 허용
    admin_api_version: v3 # Admin API 버전 v3 사용
    admin_key_required: true # Admin API 접근 시 키 필요
    admin_key:
      - name: admin
        key: "1234qwer!!" # 실제 운영 환경에서는 보다 복잡한 값으로 변경할 것
        role: admin
    allow_admin:
      - 0.0.0.0/0 # 필요 시 특정 IP 범위로 제한 가능
    admin_listen:
      ip: 0.0.0.0
      port: 9180

discovery:
  eureka:
    host:
      - "http://10.101.99.102:8761"
    prefix: "/eureka/"
    fetch_interval: 30 # 30s
    weight: 100 # default weight for node
    timeout:
      connect: 2000 # 2000ms
      send: 2000 # 2000ms
      read: 5000 # 5000ms

plugin_attr:
  # Prometheus 모니터링 설정
  prometheus:
    export_uri: "/apisix/prometheus/metrics"
    export_addr:
      ip: "0.0.0.0"
      port: 9091

  log-rotate:
    interval: 3600    # rotate interval (unit: second)
    max_kept: 168     # max number of log files will be kept
    max_size: 10000000      # max size of log files will be kept
    enable_compression: true    # enable log file compression(gzip) or not, default false      

  opentelemetry:
    resource:
      service.name: "apisix"
      env: "prod"
    collector:
      address: "10.101.91.145:4318"   # OTLP HTTP receiver 포트
      request_timeout: 3



plugins:
  - authz-keycloak
  - aws-lambda
  - basic-auth
  - cors
  - echo
  - ext-plugin-post-req
  - ext-plugin-post-resp
  - ext-plugin-pre-req
  - file-logger
  - forward-auth
  - jwt-auth
  - kafka-logger
  - kafka-proxy
  - log-rotate
  - node-status
  - opentelemetry
  - prometheus
  - proxy-rewrite
  - public-api
  - response-rewrite
  - request-validation
  - serverless-post-function
  - serverless-pre-function
  - syslog
  # - 3rd-party
